# Generated by Django 5.1 on 2024-08-18 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='task_type',
            field=models.CharField(choices=[('Query', 'Query'), ('Techinical Issue', 'Techinical Issue'), ('Request', 'Request'), ('Other', 'Other')], default='Other', max_length=50),
        ),
    ]
